#!/usr/bin/env bash

input=$1
crf=$2
min_rate=$3
target_rate=$4
max_rate=$5
width=$6
height=$7
output=$8

tmp_dir="$(mktemp -d)"

cd "$tmp_dir"

nice -n19 ffmpeg -i "$input" \
	-tile-columns 2 -tile-rows 1 -row-mt 1 -threads 8 \
	-g 240 -quality good \
	-crf $crf -b:v "${target_rate}k" -minrate "${min_rate}k" -maxrate "${max_rate}k" \
	-c:v libvpx-vp9 -an \
	-filter:v "scale='min(${width},iw)':min'(${height},ih)':force_original_aspect_ratio=decrease" \
	-pass 1 \
	-y "${output}" && \
nice -n19 ffmpeg -i "$input" \
	-tile-columns 2 -tile-rows 1 -row-mt 1 -threads 8 \
	-g 240 -quality good \
	-crf $crf -b:v "${target_rate}k" -minrate "${min_rate}k" -maxrate "${max_rate}k" \
	-c:v libvpx-vp9 -c:a libopus \
	-filter:v "scale='min(${width},iw)':min'(${height},ih)':force_original_aspect_ratio=decrease" \
	-pass 2 \
	-speed 2 \
	-y "${output}"

cd -
rm -rf "$tmp_dir"
