#!/usr/bin/env bash

input=$1
crf=$2
min_rate=$3
target_rate=$4
max_rate=$5
max_width=$6
max_height=$7
output=$8

nice -n19 av1an -i "$input" \
	-enc vpx -v "--codec=vp9 --end-usage=cq --cq-level=${crf} --target-bitrate=${max_rate} --good --cpu-used=2 --tile-columns=2 --tile-rows=1" \
	--webm --audio_params='-c:a libopus' -r -fmt yuv420p
